USE REG IN 2
USE REGH IN 1

SELECT REG
SET ORDER TO 1
SET FILTER TO np>0


SCAN
	SELECT REGH
		APPEND BLANK
		Replace ID WITH REG.ID,FECHA WITH REG.FPAR,CLAVE WITH 1,REG.STAT WITH 'FRESC'
		IF REG.NS>0
		APPEND BLANK
		replace id WITH reg.id,fecha WITH REG.ucal,clave WITH 5
		ENDIF
		
		SELECT REG
		
ENDSCAN

SELECT REGH
BROWSE