PROCEDURE R4
*---------------------------------------------------------------------*
PARAMETERS COLS,ROWS,COLW,FIELD
DO WHILE MOD(RECCOUNT(),COLS) # 0
APPE BLANK
ENDD
GO TOP
PGCOUNT=1
PRINTED=0
NVAC=0
SET CONS OFF
SET PRIN ON
*----------------------------
*  Cambio a Letra 17 cpi
	???&q21
*----------------------------
DO WHILE PRINTED<RECCOUNT() &&
?'  Rancho   : '+Q36+'   '+nom 
?'  Area     : VIENTRES'
?'  Reporte  : '+NTIT
?'  Fecha    : '+DTOC(DATE())+'  Hora : '+TIME()
?'  Pagina   : '+STR(PGCOUNT,2,0)+space(100)+[DAIRYFOX]
?'  Periodo  : '+NTIT2+'  x ID'
?'  '+REPLI(CHR(254),132)
*?
*?'      ID    ID'
*?SPACE(1),REPLI('-',132)
ONTHISPAGE=MIN(ROWS*COLS,RECCOUNT()-PRINTED)
ROWS=MIN(ROWS,(ONTHISPAGE/COLS))
THISROW=1
DO WHILE THISROW<=ROWS and PRINTED<=RECCOUNT()
THISCOL=1
if ID>0
?space(1),LEFT(STR(ID,5,0),COLW)+SPACE(MAX(0,COLW-LEN(FIELD)))
NVAC=NVAC+1
endi
PRINTED=PRINTED+1
DO WHILE THISCOL<COLS and PRINTED<=RECCOUNT()
SKIP ROWS
if ID>0
??space(1),LEFT(STR(ID,5,0),COLW)+SPACE(MAX(0,COLW-LEN(FIELD)))
NVAC=NVAC+1
endi
THISCOL=THISCOL+1
PRINTED=PRINTED+1
ENDD
THISROW=THISROW+1
SKIP (((COLS-1)*ROWS)-1)*-1

IF THISROW-1=ROWS and PRINTED<RECCOUNT()
?'  '+REPLI(CHR(254),132)
ENDI

IF PRINTED=RECCOUNT() 
?'  '+REPLI(CHR(254),132)
?'  TOTAL = '+STR(NVAC,4,0)
ENDI
ENDD
EJECT
PGCOUNT=PGCOUNT+1
SKIP ((COLS-1)*ROWS)
ENDD
CLOS DATA
ERAS LOTES.DBF

PROCEDURE R5
* LISTADO DE Vientres A BST
*---------------------------------------------------------------------*
PARAMETERS COLS,ROWS,COLW,FIELD
DO WHILE MOD(RECCOUNT(),COLS) # 0
APPE BLANK
ENDD
GO TOP
PGCOUNT=1
PRINTED=0
NVAC=0

DO WHILE PRINTED<RECCOUNT() &&
?'  Hato     : '+Q36+'   '+nom 
?'  Area     : VIENTRES'
?'  Reporte  : LISTADO DE VIENTRES A BST'
?'  Fecha    : '+DTOC(DATE())+'  Hora : '+TIME()
?'  Pagina   : '+STR(PGCOUNT,2,0)+space(60)+TVersion
?'  Periodo  : '+FBST.Combo1.Value
?'  '+REPLI('-',95)
?
?'    ID Lote     ID Lote     ID Lote     ID Lote     ID Lote     ID Lote     ID Lote     ID Lote'
?SPACE(1),REPLI('-',95)
ONTHISPAGE=MIN(ROWS*COLS,RECCOUNT()-PRINTED)
ROWS=MIN(ROWS,(ONTHISPAGE/COLS))
THISROW=1
DO WHILE THISROW<=ROWS and PRINTED<=RECCOUNT()
THISCOL=1
if ID>0
?space(2),LEFT(STR(ID,5,0)+' '+STR(corr,2),COLW)+SPACE(MAX(0,COLW-LEN(FIELD)))
NVAC=NVAC+1
endi
PRINTED=PRINTED+1
DO WHILE THISCOL<COLS and PRINTED<=RECCOUNT()
SKIP ROWS
if ID>0
??space(2),LEFT(STR(ID,5,0)+' '+STR(corr,2),COLW)+SPACE(MAX(0,COLW-LEN(FIELD)))
NVAC=NVAC+1
endi
THISCOL=THISCOL+1
PRINTED=PRINTED+1
ENDD
THISROW=THISROW+1
SKIP (((COLS-1)*ROWS)-1)*-1

IF THISROW-1=ROWS and PRINTED<RECCOUNT()
?'  '+REPLI('-',95)
ENDI

IF PRINTED=RECCOUNT() 
?'  '+REPLI('-',95)
?
?'   TOTAL = '+STR(NVAC,4)
ENDI
ENDD
EJECT
PGCOUNT=PGCOUNT+1
SKIP ((COLS-1)*ROWS)
ENDD
Use
Erase LOTES.DBF
RETURN


PROCEDURE R55
* LISTADO DE Animales a Vacunacion Por Grupo
*-------------------------------------------
PARAMETERS COLS,ROWS,COLW,FIELD
DO WHILE MOD(RECCOUNT(),COLS) # 0
APPE BLANK
ENDD
GO TOP
PGCOUNT=1
PRINTED=0
NVAC=0

DO WHILE PRINTED<RECCOUNT() &&
?'  Hato     : '+Q36+'   '+nom 
?'  Area     : '+xAREA
?'  Reporte  : LISTADO DE ANIMALES A VACUNACION'
?'  Fecha    : '+DTOC(DATE())+'  Hora : '+TIME()
?'  Pagina   : '+STR(PGCOUNT,2,0)+space(60)+TVersion
?'  Vacuna   : '+GNVACUNA.NOMBRE+"  "+xTIT2
?'  '+REPLI('-',95)
?
?'     ID Lote      ID Lote      ID Lote      ID Lote      ID Lote      ID Lote      ID Lote'
?SPACE(1),REPLI('-',95)
ONTHISPAGE=MIN(ROWS*COLS,RECCOUNT()-PRINTED)
ROWS=MIN(ROWS,(ONTHISPAGE/COLS))
THISROW=1
DO WHILE THISROW<=ROWS and PRINTED<=RECCOUNT()
THISCOL=1
if ID>0
?space(2),LEFT(STR(ID,5,0)+' '+STR(corr,3),COLW)+SPACE(MAX(0,COLW-LEN(FIELD)))
NVAC=NVAC+1
endi
PRINTED=PRINTED+1
DO WHILE THISCOL<COLS and PRINTED<=RECCOUNT()
SKIP ROWS
if ID>0
??space(2),LEFT(STR(ID,5,0)+' '+STR(corr,3),COLW)+SPACE(MAX(0,COLW-LEN(FIELD)))
NVAC=NVAC+1
endi
THISCOL=THISCOL+1
PRINTED=PRINTED+1
ENDD
THISROW=THISROW+1
SKIP (((COLS-1)*ROWS)-1)*-1

IF THISROW-1=ROWS and PRINTED<RECCOUNT()
?'  '+REPLI('-',95)
ENDI

IF PRINTED=RECCOUNT() 
?'  '+REPLI('-',95)
?
?'   TOTAL = '+STR(NVAC,4)
ENDI
ENDD
EJECT
PGCOUNT=PGCOUNT+1
SKIP ((COLS-1)*ROWS)
ENDD
Use
Erase LOTES.DBF
RETURN



PROCEDURE R60
* LISTADO DE Animales a Movimiento de Lote
*-------------------------------------------
PARAMETERS COLS,ROWS,COLW,FIELD,xLOTE
DO WHILE MOD(RECCOUNT(),COLS) # 0
APPE BLANK
ENDD
GO TOP
PGCOUNT=1
PRINTED=0
NVAC=0

DO WHILE PRINTED<RECCOUNT() &&
?'  Hato     : '+Q36+'   '+nom 
?'  Area     : '+xAREA
?'  Reporte  : LISTADO DE ANIMALES PARA CAMBIO DE LOTE'
?'  Fecha    : '+DTOC(DATE())+'  Hora : '+TIME()
?'  Pagina   : '+STR(PGCOUNT,2,0)+space(60)+TVersion
?'  Al Lote  :  '+xLOTE+"  "+xTIT2
?'  '+REPLI('-',95)
?
?'     ID Lote      ID Lote      ID Lote      ID Lote      ID Lote      ID Lote      ID Lote'
?SPACE(1),REPLI('-',95)
ONTHISPAGE=MIN(ROWS*COLS,RECCOUNT()-PRINTED)
ROWS=MIN(ROWS,(ONTHISPAGE/COLS))
THISROW=1
DO WHILE THISROW<=ROWS and PRINTED<=RECCOUNT()
THISCOL=1
if ID>0
?space(2),LEFT(STR(ID,5,0)+' '+STR(corr,3),COLW)+SPACE(MAX(0,COLW-LEN(FIELD)))
NVAC=NVAC+1
endi
PRINTED=PRINTED+1
DO WHILE THISCOL<COLS and PRINTED<=RECCOUNT()
SKIP ROWS
if ID>0
??space(2),LEFT(STR(ID,5,0)+' '+STR(corr,3),COLW)+SPACE(MAX(0,COLW-LEN(FIELD)))
NVAC=NVAC+1
endi
THISCOL=THISCOL+1
PRINTED=PRINTED+1
ENDD
THISROW=THISROW+1
SKIP (((COLS-1)*ROWS)-1)*-1

IF THISROW-1=ROWS and PRINTED<RECCOUNT()
?'  '+REPLI('-',95)
ENDI

IF PRINTED=RECCOUNT() 
?'  '+REPLI('-',95)
?
?'   TOTAL = '+STR(NVAC,4)
ENDI
ENDD
EJECT
PGCOUNT=PGCOUNT+1
SKIP ((COLS-1)*ROWS)
ENDD
Use
Erase LOTES.DBF
RETURN









