SET TALK OFF
SET DATE ANSI
SET CENTURY on
B=CTOD("")

USE c:\lacto2006\lx1\reg
SELECT reg
SET ORDER TO 2

COPY TO IPHONE FIELDS ID,NP,EDAD,CORR,DPR,DIA,NS,PRM,DSC,STAT FOR FB2=B DELIMITED WITH CHARACTER '|'

MODIFY FILE IPHONE
CLOSE DATABASES
 