*PARAMETER xCDIAS
PROCEDURE REVENTOS
PRIVATE xc

IF NOT FILE("REVENTOS2.DBF")
	CREATE TABLE REVENTOS (ID n(5),NP n(2),FECHA d(8),EVENTO n(2),CEVENTO c(12),STAT c(5),NS n(2),FECHA2 d(8))

	USE REVENTOS IN 11 ALIAS REV EXCLUSIVE
	SELECT REV
	ZAP

SELECT REG
SET ORDER TO 2
SCAN
	SELECT REV
	APPEND BLANK
	REPLACE REV.ID WITH REG.ID,REV.NP WITH REG.NP,REV.FECHA WITH REG.FPAR,REV.EVENTO WITH 1,REV.CEVENTO WITH 'Parto',REV.STAT WITH 'FRESC'
	SELECT REG
ENDSCAN	

*------------
SELECT CALOR
SET ORDER TO 2
SET FILTER TO (CLAVE=5 OR CLAVE=6 OR CLAVE=9)
SCAN
	SELECT REV
	SCAN FOR CALOR.ID=REV.ID 

	IF CALOR.NP=REV.NP
		APPEND BLANK
		REPLACE REV.ID WITH CALOR.ID,REV.NP WITH CALOR.NP,REV.FECHA WITH CALOR.FECHA,REV.EVENTO WITH CALOR.CLAVE,REV.NS WITH CALOR.SER ,REV.FECHA2 WITH CALOR.FECHA2,REV.STAT WITH CALOR.STAT
		REPLACE REV.CEVENTO WITH ICASE(CALOR.CLAVE=3,'Tratamiento',CALOR.CLAVE=4,'Celo',CALOR.CLAVE=5,'Inseminacion',CALOR.CLAVE=6,'Dx Gestacion',CALOR.CLAVE=9,'Aborto')
	ENDIF

	ENDSCAN

SELECT CALOR
ENDSCAN

*-------------------	
SELECT REG
SET ORDER TO 2
SCAN

	IF REG.FPSV#B
	SELECT REV
	APPEND BLANK
	REPLACE REV.ID WITH REG.ID,REV.NP WITH REG.NP,REV.FECHA WITH REG.FPSV,REV.EVENTO WITH 21,REV.CEVENTO WITH 'PSV'
	ENDIF
	
	
	IF REG.FB2#B
	SELECT REV
	APPEND BLANK
	REPLACE REV.ID WITH REG.ID,REV.NP WITH REG.NP,REV.FECHA WITH REG.FB2,REV.EVENTO WITH 22,REV.CEVENTO WITH 'BAJA'
	ENDIF
	
	SELECT REG
ENDSCAN	
*------------------

SELECT REV
INDEX ON ID TAG ID
browse
COPY TO REVENTOS2
ELSE
ENDIF
?'aqui estoy'
wait

RETURN